name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the problem this feature would solve.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your proposed solution.
    validations:
      required: true
